# Generated by Django 3.2 on 2022-01-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadesmedicos',
            name='id_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
    ]
