# Generated by Django 3.2 on 2022-01-27 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20220127_1934'),
        ('clinico', '0002_alter_especialidadesmedicos_id_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosSalida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cie10', models.CharField(default='', max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('usuarioRegistro', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
            ],
        ),
    ]
