# Generated by Django 3.2 on 2022-01-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0003_diagnosticos_estadossalida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos',
            name='usuarioRegistro',
        ),
    ]
