# Generated by Django 3.2 on 2022-01-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0009_auto_20220128_1657'),
        ('clinico', '0004_remove_diagnosticos_usuarioregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
    ]
