# Generated by Django 3.2 on 2022-02-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinico', '0005_servicios_sedesclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='sedesClinica',
        ),
    ]
