# Generated by Django 3.2 on 2022-01-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPlanta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='L', max_length=1)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('estado', models.CharField(max_length=1)),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
                ('id_tiposPlanta', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.tiposplanta')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesPlanta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
                ('id_perfilPlanta', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.tiposplanta')),
                ('id_tipo_doc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento')),
            ],
        ),
    ]
