# Generated by Django 3.2 on 2022-01-27 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('sitios', '0007_auto_20220127_1439'),
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilesplanta',
            old_name='id_perfilPlanta',
            new_name='tiposPlanta',
        ),
        migrations.RenameField(
            model_name='planta',
            old_name='id_tipo_doc',
            new_name='tipoDoc',
        ),
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='id_tipo_doc',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='id_tiposPlanta',
        ),
        migrations.AddField(
            model_name='perfilesplanta',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='perfilesplanta',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='perfilesplanta',
            name='planta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='perfilesplanta',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='perfilesplanta',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='planta',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='planta',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.sedesclinica'),
        ),
        migrations.AddField(
            model_name='planta',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='tiposplanta',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tiposplanta',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tiposplanta',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
    ]
