# Generated by Django 3.2 on 2022-01-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_auto_20220127_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilesplanta',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='tiposplanta',
            name='usuarioRegistro',
        ),
    ]
