# Generated by Django 3.2 on 2022-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_auto_20220127_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedesclinica',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
    ]
