# Generated by Django 3.2 on 2022-01-27 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('sitios', '0005_alter_sedesclinica_estadoreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centros',
            old_name='id_ciudad',
            new_name='ciudades',
        ),
        migrations.RenameField(
            model_name='centros',
            old_name='id_departamento',
            new_name='departamentos',
        ),
        migrations.RenameField(
            model_name='ciudades',
            old_name='id_departamento',
            new_name='departamentos',
        ),
        migrations.RemoveField(
            model_name='centros',
            name='estado',
        ),
        migrations.AddField(
            model_name='centros',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='centros',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='centros',
            name='ubicacion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='centros',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='centros',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ciudades',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
