# Generated by Django 3.2 on 2022-01-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0007_auto_20220127_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centros',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='departamentos',
            name='usuarioRegistro',
        ),
        migrations.RemoveField(
            model_name='sedesclinica',
            name='usuarioRegistro',
        ),
    ]
