# Generated by Django 3.2 on 2022-01-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos',
            name='factura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='numcita',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='salidaClinica',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
