# Generated by Django 3.2 on 2022-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0005_alter_ingresos_usuarioregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='salidaDefinitiva',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
