# Generated by Django 3.2 on 2022-01-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0006_ingresos_salidadefinitiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='serviciosActual',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='serviciosIng',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='serviciosSalida',
        ),
    ]
