# Generated by Django 3.2 on 2022-01-27 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_centro',
            new_name='centrosC',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_tipo_doc',
            new_name='tipoDoc',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_tiposUsuario',
            new_name='tiposUsuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='estado',
        ),
        migrations.AddField(
            model_name='tiposdocumento',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tiposdocumento',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tiposdocumento',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='tiposusuario',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tiposusuario',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tiposusuario',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estadoReg',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='tiposdocumento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tiposusuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
