# Generated by Django 3.2 on 2022-01-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_auto_20220127_1511'),
        ('usuarios', '0003_alter_usuarios_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
    ]
